//! Facts about checked regions of Wasm linear memory.

use cranelift_codegen::cursor::{Cursor, FuncCursor};
use cranelift_codegen::dominator_tree::DominatorTree;
use cranelift_codegen::flowgraph::ControlFlowGraph;
use cranelift_codegen::ir::condcodes::{CondCode, IntCC};
use cranelift_codegen::ir::{self, Block, Function, Inst, InstBuilder, Opcode, Value};
use std::collections::HashSet;
use wasmtime_environ::MemoryIndex;

/// A region whose complete byte range has already been bounds-checked.
#[derive(Clone, Copy, Debug)]
struct CheckedSpan {
    /// Which Wasm linear memory contains this region.
    memory: MemoryIndex,

    /// The original 32-bit Wasm address where the region begins.
    wasm_base: Value,

    /// The host pointer corresponding to `wasm_base`.
    native_base: Value,

    /// Number of checked bytes beginning at `wasm_base`.
    len: u32,
}

#[derive(Clone, Copy, Debug)]
struct MemoryAccess {
    /// The memory being accessed.
    memory: MemoryIndex,

    /// The original 32-bit address supplied by Wasm.
    wasm_addr: Value,

    /// The host address currently generated by Cranelift.
    native_addr: Value,

    /// The constant offset encoded in the Wasm load/store.
    static_offset: u32,

    /// Number of bytes read or written.
    access_size: u8,
}

/// Facts collected while translating one Wasm function.
#[derive(Default)]
pub(crate) struct State {
    spans: Vec<CheckedSpan>,
    accesses: Vec<MemoryAccess>,
}

impl State {
    /// Records that the complete range `[wasm_base, wasm_base + len)` has
    /// passed a bounds check and begins at `native_base`.
    pub(crate) fn record_span(
        &mut self,
        memory: MemoryIndex,
        wasm_base: Value,
        native_base: Value,
        len: u32,
    ) {
        self.spans.push(CheckedSpan {
            memory,
            wasm_base,
            native_base,
            len,
        })
    }

    pub(crate) fn record_access(
        &mut self,
        memory: MemoryIndex,
        wasm_addr: Value,
        native_addr: Value,
        static_offset: u32,
        access_size: u8,
    ) {
        self.accesses.push(MemoryAccess {
            memory,
            wasm_addr,
            native_addr,
            static_offset,
            access_size,
        });
    }

    pub(crate) fn optimize(self, func: &mut Function) -> usize {
        let cfg = ControlFlowGraph::with_function(func);
        let domtree = DominatorTree::with_function(func, &cfg);
        let mut rewrites = Vec::new();
        let mut rewritten_insts = HashSet::new();

        for access in self.accesses {
            let Some(old_addr_inst) = func.dfg.value_def(access.native_addr).inst() else {
                continue;
            };
            let Some(access_block) = func.layout.inst_block(old_addr_inst) else {
                continue;
            };

            for span in self.spans.iter().copied() {
                if span.memory != access.memory {
                    continue;
                }

                let Some(native_base_inst) = func.dfg.value_def(span.native_base).inst() else {
                    continue;
                };

                if !domtree.dominates(native_base_inst, old_addr_inst, &func.layout) {
                    continue;
                }

                let Some((index, shift)) =
                    scaled_offset_from_base(func, access.wasm_addr, span.wasm_base)
                else {
                    continue;
                };

                let (index_max, mask) = match band_mask(func, index) {
                    // The source already masks the index, so no new mask is needed.
                    Some(mask) => (mask, None),

                    // Otherwise, try to obtain a bound from dominating control flow.
                    None => {
                        let Some(max) =
                            dominating_unsigned_upper_bound(func, &domtree, index, access_block)
                        else {
                            continue;
                        };

                        // `index & max` preserves every value in 0..=max only
                        // when max is one less than a power of two.
                        if max & max.wrapping_add(1) != 0 {
                            continue;
                        }

                        (max, Some(max))
                    }
                };

                let Some(dynamic_max) = u64::from(index_max).checked_shl(u32::from(shift)) else {
                    continue;
                };

                let end = dynamic_max
                    .checked_add(u64::from(access.static_offset))
                    .and_then(|n| n.checked_add(u64::from(access.access_size)));

                if !end.is_some_and(|end| end <= u64::from(span.len)) {
                    continue;
                }

                if !rewritten_insts.insert(old_addr_inst) {
                    break;
                }

                rewrites.push(Rewrite {
                    old_addr_inst,
                    native_base: span.native_base,
                    index,
                    shift,
                    static_offset: access.static_offset,
                    mask,
                });
                break;
            }
        }

        let count = rewrites.len();
        for rewrite in rewrites {
            apply_rewrite(func, rewrite);
        }
        count
    }
}

#[derive(Clone, Copy)]
struct Rewrite {
    old_addr_inst: Inst,
    native_base: Value,
    index: Value,
    shift: u8,
    static_offset: u32,
    /// A mask inserted for speculative safety. This is `None` when the
    /// original Wasm expression already contains the mask.
    mask: Option<u32>,
}

fn scaled_offset_from_base(func: &Function, addr: Value, base: Value) -> Option<(Value, u8)> {
    let dynamic_offset = offset_from_base(func, addr, base)??;
    scaled_offset(func, dynamic_offset)
}

fn offset_from_base(func: &Function, addr: Value, base: Value) -> Option<Option<Value>> {
    let addr = func.dfg.resolve_aliases(addr);
    let base = func.dfg.resolve_aliases(base);

    if addr == base {
        return Some(None);
    }

    let inst = func.dfg.value_def(addr).inst()?;
    if func.dfg.insts[inst].opcode() != Opcode::Iadd {
        return None;
    }

    let args = func.dfg.inst_args(inst);
    if func.dfg.resolve_aliases(args[0]) == base {
        Some(Some(args[1]))
    } else if func.dfg.resolve_aliases(args[1]) == base {
        Some(Some(args[0]))
    } else {
        None
    }
}

fn scaled_offset(func: &Function, value: Value) -> Option<(Value, u8)> {
    let value = func.dfg.resolve_aliases(value);
    let inst = func.dfg.value_def(value).inst()?;

    if func.dfg.insts[inst].opcode() != Opcode::Ishl {
        return None;
    }

    let args = func.dfg.inst_args(inst);
    let shift = u8::try_from(iconst_u32(func, args[1])?).ok()?;
    (shift < 32).then_some((args[0], shift))
}

fn band_mask(func: &Function, value: Value) -> Option<u32> {
    let value = func.dfg.resolve_aliases(value);
    let inst = func.dfg.value_def(value).inst()?;

    if func.dfg.insts[inst].opcode() != Opcode::Band {
        return None;
    }

    let args = func.dfg.inst_args(inst);
    iconst_u32(func, args[0]).or_else(|| iconst_u32(func, args[1]))
}

fn iconst_u32(func: &Function, value: Value) -> Option<u32> {
    let value = func.dfg.resolve_aliases(value);

    if func.dfg.value_type(value) != ir::types::I32 {
        return None;
    }

    let inst = func.dfg.value_def(value).inst()?;
    let ir::InstructionData::UnaryImm {
        opcode: Opcode::Iconst,
        imm,
    } = func.dfg.insts[inst]
    else {
        return None;
    };

    Some(
        u32::try_from(imm.bits().cast_unsigned() & u64::from(u32::MAX))
            .expect("an i32 immediate fits in u32"),
    )
}

fn strip_boolean_casts(func: &Function, mut value: Value) -> Value {
    loop {
        let Some(inst) = func.dfg.value_def(value).inst() else {
            return value;
        };

        match func.dfg.insts[inst].opcode() {
            // Extending zero or one preserves whether the condition is true.
            Opcode::Uextend => value = func.dfg.inst_args(inst)[0],
            _ => return value,
        }
    }
}

fn dominating_unsigned_upper_bound(
    func: &Function,
    domtree: &DominatorTree,
    value: Value,
    access_block: Block,
) -> Option<u32> {
    let value = func.dfg.resolve_aliases(value);
    let mut result = None;

    for block in func.layout.blocks() {
        if block == access_block || !domtree.block_dominates(block, access_block) {
            continue;
        }

        let Some(branch) = func.layout.last_inst(block) else {
            continue;
        };

        let ir::InstructionData::Brif {
            arg,
            blocks: [then_block, else_block],
            ..
        } = func.dfg.insts[branch]
        else {
            continue;
        };

        let then_dominates =
            domtree.block_dominates(then_block.block(&func.dfg.value_lists), access_block);
        let else_dominates =
            domtree.block_dominates(else_block.block(&func.dfg.value_lists), access_block);

        let condition_is_true = match (then_dominates, else_dominates) {
            (true, false) => true,
            (false, true) => false,
            _ => continue,
        };

        let condition = strip_boolean_casts(func, arg);
        let Some(compare) = func.dfg.value_def(condition).inst() else {
            continue;
        };

        let ir::InstructionData::IntCompare { cond, args, .. } = func.dfg.insts[compare] else {
            continue;
        };

        // If we reached the false successor, use the inverse comparison.
        let cond = if condition_is_true {
            cond
        } else {
            cond.complement()
        };

        let (cond, other) = if func.dfg.resolve_aliases(args[0]) == value {
            (cond, args[1])
        } else if func.dfg.resolve_aliases(args[1]) == value {
            (cond.swap_args(), args[0])
        } else {
            continue;
        };

        let bound = match cond {
            IntCC::UnsignedLessThan => iconst_u32(func, other).and_then(|n| n.checked_sub(1)),
            IntCC::UnsignedLessThanOrEqual => iconst_u32(func, other),
            _ => None,
        };

        if let Some(bound) = bound {
            result = Some(result.map_or(bound, |old: u32| old.min(bound)));
        }
    }

    result
}

fn apply_rewrite(func: &mut Function, rewrite: Rewrite) {
    let mut pos = FuncCursor::new(func);
    pos.goto_inst(rewrite.old_addr_inst);

    // Extend before shifting. This exposes AArch64's scaled addressing mode.
    let index = if let Some(mask) = rewrite.mask {
        pos.ins().band_imm_u(rewrite.index, i64::from(mask))
    } else {
        rewrite.index
    };
    let index64 = pos.ins().uextend(ir::types::I64, index);
    let offset64 = pos.ins().ishl_imm_u(index64, i64::from(rewrite.shift));

    let mut new_addr = pos.ins().iadd(rewrite.native_base, offset64);

    if rewrite.static_offset != 0 {
        new_addr = pos
            .ins()
            .iadd_imm_u(new_addr, i64::from(rewrite.static_offset));
    }

    let new_addr_inst = pos.func.dfg.value_def(new_addr).unwrap_inst();
    pos.func
        .dfg
        .replace_with_aliases(rewrite.old_addr_inst, new_addr_inst);
    pos.remove_inst();
}
